### ISSUE TITLE
Services are not working with Jest environment

### ISSUE THREAD

**Issue by kailin0512** [iiroj/jest-environment-webdriverio#6]
Services array like browserstack, selenium standalone, devtools and customService is not working because of the Jest environment
Also hooks like onPrepare and onComplete are also not working

Got confirmation from wdio author:
services only work when using the wdio testrunner with mocha,jasmine or cucumber, please look at this example: https://github.com/webdriverio/webdriverio/tree/main/examples/wdio/custom-service

**Comment by iiroj** [comment]
Hello,

I've decided to no longer maintain this package. I can merge your MR, but I won't be publishing new versions anymore, at least until I some use for it myself.
